defaults: &defaults
  adapter: postgresql

development:
  <<: *defaults
  database: weather-station-dev

test:
  <<: *defaults
  database: weather_station_test

production:
  <<: *defaults
  database: weather-statation-prod
